### ISSUE TITLE
pam_ldap.so x86 path

### ISSUE THREAD

**Issue by bitbybit** [lunarok/cops_ynh#8]
x86 machine will need diffrent path in `/etc/pam.d/nginx`

`/lib/i386-linux-gnu/security/pam_ldap.so`

**Comment by b01xy** [comment]
on arm (raspi2) :
 in /etc/pam.d/nginx
auth    required  /lib/arm-linux-gnueabihf/security/pam_ldap.so
account required  /lib/arm-linux-gnueabihf/security/pam_ldap.so 

I'm now able to log but white screen

**Comment by TiberiusRegenschein** [comment]
Installed COPS and followed the advice of b01xy because path provided by the installation are definitely wrong. No success. Can not enter and end up with an 401 error.
Will this nice app be updated or do I have to search for an alternative?

Thanks
