### ISSUE TITLE
New cops into YunoHost-Apps

### ISSUE THREAD

**Issue by polytan02** [lunarok/cops_ynh#9]
Hi Lunarok,

I packaged the latest version of COPS to be compatible with latest YunoHost requirements : https://github.com/YunoHost-Apps/cops_ynh

It is only once I finished that I noticed you worked on this 2 years ago. Don't see any bad behaviour about this, I just did not notice.

Are you OK if we replace your app with the one I maintain by any chance ?
Please see https://github.com/YunoHost/apps/pull/101/commits/289a65733047437739975d7846670cb920509a5d

Many thanks for your feedback.

Cheers, Polytan02

**Comment by lunarok** [comment]
no pb, not maintaining it anymore (migrate to Nextcloud)

**Comment by polytan02** [comment]
Great, thanks :)
